### ISSUE TITLE
In "Prefer-Noun-adjective-naming" why isn't it UserCurrent and ButtonGoLive

### ISSUE THREAD

**Issue by jwrightecs** [kyleshevlin/blog#151]
src/content/posts/prefer-noun-adjective-naming/index.mdx

Shouldn't it be `UserCurrent.tsx` and `ButtonGoLive.tsx`?      `FullScreen` should probably be `Fullscreen.tsx`, not `ScreenFull.tsx`  as "fullscreen" is the adjective, perhaps it needs a noun for clarity, like `WindowFullscreen.tsx`?

**Comment by kyleshevlin** [comment]
I didn't change the other names because I was just trying to highlight the differences for some of the name changes. But you're right. I could update them all.

**Comment by kyleshevlin** [comment]
Adjusted in https://github.com/kyleshevlin/blog/commit/a0c8ad70ea9a0e46530866a82570d210456fd7ad
